// Golden-vector equivalence: the TS SDK must produce byte-identical order keys, PDAs, and
// instruction data to the Rust torna-sdk (which is proven against the real engine). The
// vectors are generated by `cargo run --bin golden` (torna/sdk/src/bin/golden.rs).

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PublicKey } from "@solana/web3.js";
import { Tree } from "../src/index.js";
import { orderKey, priceOf, slotOf, Side } from "../src/keys.js";

const here = dirname(fileURLToPath(import.meta.url));
const g = JSON.parse(readFileSync(join(here, "..", "vectors", "golden.json"), "utf8"));

const program = new PublicKey(new Uint8Array(32).fill(1));
const creator = new PublicKey(new Uint8Array(32).fill(2));
const maker = new PublicKey(new Uint8Array(32).fill(3));

const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");

test("fixed pubkeys construct identically (base58)", () => {
  assert.equal(program.toBase58(), g.program);
  assert.equal(creator.toBase58(), g.creator);
  assert.equal(maker.toBase58(), g.maker);
});

test("order_key bytes match the Rust SDK", () => {
  for (const c of g.orderKeys) {
    const side = c.side === 0 ? Side.Ask : Side.Bid;
    const k = orderKey(side, BigInt(c.price), BigInt(c.slot), maker, BigInt(c.nonce));
    assert.equal(hex(k), c.hex, `order_key side=${c.side} price=${c.price} slot=${c.slot} nonce=${c.nonce}`);
    // round-trip the decoders too
    assert.equal(priceOf(side, k), BigInt(c.price));
    assert.equal(slotOf(k), BigInt(c.slot));
  }
});

test("PDAs match the Rust SDK", () => {
  const t = new Tree(program, creator, g.treeId);
  assert.equal(t.headerPda()[0].toBase58(), g.pdas.header);
  assert.equal(t.allocPda()[0].toBase58(), g.pdas.alloc);
  assert.equal(t.nodePda(3n)[0].toBase58(), g.pdas.node3);
});

test("init_tree_ix data + accounts match the Rust SDK", () => {
  const t = new Tree(program, creator, g.treeId);
  const i = g.initTreeIx;
  const ix = t.initTreeIx(maker, i.valueSize, i.fanout, BigInt(i.rentHdr), BigInt(i.rentAlloc));
  assert.equal(hex(ix.data), i.dataHex, "init_tree data (incl canonical bumps)");
  assert.deepEqual(ix.keys.map((k) => k.pubkey.toBase58()), i.accounts);
});
